name: Pipeline de Despliegue Continuo (CD)

on:
  push:
    branches:
      - main 

jobs:
  desplegar-nueva-version:
    name: Compilar, Probar y Crear Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar Pruebas
        run: python scripts/test_carta.py

      - name: Crear Release en GitHub
        uses: actions/create-release@v1
        env:
          GITHUB¡Hola JG! Tienes una excelente intuición.
